"""WhatsApp SDK Pydantic models.

These models provide type-safe data structures for the WhatsApp Business API.
"""

from .base import (
    BaseResponse,
    Contact,
    Error,
    ErrorResponse,
    Message,
    MessageResponse,
    PaginationCursor,
    PaginationInfo,
)
from .messages import (
    # Text message
    TextMessage,
    # Media messages
    ImageMessage,
    DocumentMessage,
    AudioMessage,
    VideoMessage,
    StickerMessage,
    # Location
    LocationMessage,
    # Interactive
    InteractiveMessage,
    InteractiveHeader,
    InteractiveBody,
    InteractiveFooter,
    InteractiveAction,
    Button,
    Section,
    # Template
    TemplateMessage,
    TemplateLanguage,
    TemplateComponent,
    TemplateParameter,
    # Reaction
    ReactionMessage,
    # Status
    MessageStatus,
)
from .contacts import (
    Name,
    Phone,
    Email,
    Address,
    Organization,
    Url,
    Contact,
    ContactMessage,
    ReceivedContact,
)
from .templates import (
    Template,
    TemplateButton,
    TemplateComponentDefinition,
    TemplateExample,
    TemplateResponse,
    TemplateListResponse,
    TemplateDeleteResponse,
    MessageTemplateUpdate,
    TemplateAnalytics,
)
from .media import (
    MediaUploadResponse,
    MediaURLResponse,
    MediaDeleteResponse,
    MediaUploadRequest,
    SupportedMediaTypes,
    ResumableUploadSession,
)
from .webhooks import (
    WebhookEvent,
    WebhookEntry,
    WebhookChange,
    WebhookValue,
    WebhookMessage,
    WebhookStatus,
    WebhookMetadata,
    WebhookContact,
    WebhookVerification,
    # Message types
    WebhookTextMessage,
    WebhookImageMessage,
    WebhookVideoMessage,
    WebhookAudioMessage,
    WebhookDocumentMessage,
    WebhookLocationMessage,
    WebhookStickerMessage,
    WebhookInteractiveMessage,
    WebhookReactionMessage,
    WebhookButtonReply,
    WebhookListReply,
    WebhookContext,
)

__all__ = [
    # Base models
    "BaseResponse",
    "Contact",
    "Error",
    "ErrorResponse",
    "Message",
    "MessageResponse",
    "PaginationCursor",
    "PaginationInfo",
    # Message models
    "TextMessage",
    "ImageMessage",
    "DocumentMessage",
    "AudioMessage",
    "VideoMessage",
    "StickerMessage",
    "LocationMessage",
    "InteractiveMessage",
    "InteractiveHeader",
    "InteractiveBody",
    "InteractiveFooter",
    "InteractiveAction",
    "Button",
    "Section",
    "TemplateMessage",
    "TemplateLanguage",
    "TemplateComponent",
    "TemplateParameter",
    "ReactionMessage",
    "MessageStatus",
    # Contact models
    "Name",
    "Phone",
    "Email",
    "Address",
    "Organization",
    "Url",
    "Contact",
    "ContactMessage",
    "ReceivedContact",
    # Template management models
    "Template",
    "TemplateButton",
    "TemplateComponentDefinition",
    "TemplateExample",
    "TemplateResponse",
    "TemplateListResponse",
    "TemplateDeleteResponse",
    "MessageTemplateUpdate",
    "TemplateAnalytics",
    # Media models
    "MediaUploadResponse",
    "MediaURLResponse",
    "MediaDeleteResponse",
    "MediaUploadRequest",
    "SupportedMediaTypes",
    "ResumableUploadSession",
    # Webhook models
    "WebhookEvent",
    "WebhookEntry",
    "WebhookChange",
    "WebhookValue",
    "WebhookMessage",
    "WebhookStatus",
    "WebhookMetadata",
    "WebhookContact",
    "WebhookVerification",
    "WebhookTextMessage",
    "WebhookImageMessage",
    "WebhookVideoMessage",
    "WebhookAudioMessage",
    "WebhookDocumentMessage",
    "WebhookLocationMessage",
    "WebhookStickerMessage",
    "WebhookInteractiveMessage",
    "WebhookReactionMessage",
    "WebhookButtonReply",
    "WebhookListReply",
    "WebhookContext",
]